///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyCategoriesModelStatus = 'status';
const String _jsonKeyCategoriesModelMessage = 'message';
const String _jsonKeyCategoriesModelData = 'data';
const String _jsonKeyCategoriesModelDataCurrentPage = 'current_page';
const String _jsonKeyCategoriesModelDataData = 'data';
const String _jsonKeyCategoriesModelDataFirstPageUrl = 'first_page_url';
const String _jsonKeyCategoriesModelDataFrom = 'from';
const String _jsonKeyCategoriesModelDataLastPage = 'last_page';
const String _jsonKeyCategoriesModelDataLastPageUrl = 'last_page_url';
const String _jsonKeyCategoriesModelDataNextPageUrl = 'next_page_url';
const String _jsonKeyCategoriesModelDataPath = 'path';
const String _jsonKeyCategoriesModelDataPerPage = 'per_page';
const String _jsonKeyCategoriesModelDataPrevPageUrl = 'prev_page_url';
const String _jsonKeyCategoriesModelDataTo = 'to';
const String _jsonKeyCategoriesModelDataTotal = 'total';
const String _jsonKeyCategoriesModelDataDataId = 'id';
const String _jsonKeyCategoriesModelDataDataName = 'name';
const String _jsonKeyCategoriesModelDataDataImage = 'image';
class CategoriesModelDataData {
/*
{
  "id": 44,
  "name": "اجهزه الكترونيه",
  "image": "https://student.valuxapps.com/storage/uploads/categories/16301438353uCFh.29118.jpg"
}
*/

  int? id;
  String? name;
  String? image;

  CategoriesModelDataData({
    this.id,
    this.name,
    this.image,
  });
  CategoriesModelDataData.fromJson(Map<String, dynamic> json) {
    id = int.tryParse(json[_jsonKeyCategoriesModelDataDataId]?.toString() ?? '');
    name = json[_jsonKeyCategoriesModelDataDataName]?.toString();
    image = json[_jsonKeyCategoriesModelDataDataImage]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyCategoriesModelDataDataId] = id;
    data[_jsonKeyCategoriesModelDataDataName] = name;
    data[_jsonKeyCategoriesModelDataDataImage] = image;
    return data;
  }
}

class CategoriesModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 44,
      "name": "اجهزه الكترونيه",
      "image": "https://student.valuxapps.com/storage/uploads/categories/16301438353uCFh.29118.jpg"
    }
  ],
  "first_page_url": "https://student.valuxapps.com/api/categories?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://student.valuxapps.com/api/categories?page=1",
  "next_page_url": "https://student.valuxapps.com/api/categories?page=1",
  "path": "https://student.valuxapps.com/api/categories",
  "per_page": 35,
  "prev_page_url": "https://student.valuxapps.com/api/categories?page=1",
  "to": 5,
  "total": 5
}
*/

  int? currentPage;
  List<CategoriesModelDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  CategoriesModelData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  CategoriesModelData.fromJson(Map<String, dynamic> json) {
    currentPage = int.tryParse(json[_jsonKeyCategoriesModelDataCurrentPage]?.toString() ?? '');
    if (json[_jsonKeyCategoriesModelDataData] != null && (json[_jsonKeyCategoriesModelDataData] is List)) {
      final v = json[_jsonKeyCategoriesModelDataData];
      final arr0 = <CategoriesModelDataData>[];
      v.forEach((v) {
        arr0.add(CategoriesModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json[_jsonKeyCategoriesModelDataFirstPageUrl]?.toString();
    from = int.tryParse(json[_jsonKeyCategoriesModelDataFrom]?.toString() ?? '');
    lastPage = int.tryParse(json[_jsonKeyCategoriesModelDataLastPage]?.toString() ?? '');
    lastPageUrl = json[_jsonKeyCategoriesModelDataLastPageUrl]?.toString();
    nextPageUrl = json[_jsonKeyCategoriesModelDataNextPageUrl]?.toString();
    path = json[_jsonKeyCategoriesModelDataPath]?.toString();
    perPage = int.tryParse(json[_jsonKeyCategoriesModelDataPerPage]?.toString() ?? '');
    prevPageUrl = json[_jsonKeyCategoriesModelDataPrevPageUrl]?.toString();
    to = int.tryParse(json[_jsonKeyCategoriesModelDataTo]?.toString() ?? '');
    total = int.tryParse(json[_jsonKeyCategoriesModelDataTotal]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyCategoriesModelDataCurrentPage] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyCategoriesModelDataData] = arr0;
    }
    data[_jsonKeyCategoriesModelDataFirstPageUrl] = firstPageUrl;
    data[_jsonKeyCategoriesModelDataFrom] = from;
    data[_jsonKeyCategoriesModelDataLastPage] = lastPage;
    data[_jsonKeyCategoriesModelDataLastPageUrl] = lastPageUrl;
    data[_jsonKeyCategoriesModelDataNextPageUrl] = nextPageUrl;
    data[_jsonKeyCategoriesModelDataPath] = path;
    data[_jsonKeyCategoriesModelDataPerPage] = perPage;
    data[_jsonKeyCategoriesModelDataPrevPageUrl] = prevPageUrl;
    data[_jsonKeyCategoriesModelDataTo] = to;
    data[_jsonKeyCategoriesModelDataTotal] = total;
    return data;
  }
}

class CategoriesModel {
/*
{
  "status": true,
  "message": "",
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 44,
        "name": "اجهزه الكترونيه",
        "image": "https://student.valuxapps.com/storage/uploads/categories/16301438353uCFh.29118.jpg"
      }
    ],
    "first_page_url": "https://student.valuxapps.com/api/categories?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://student.valuxapps.com/api/categories?page=1",
    "next_page_url": "https://student.valuxapps.com/api/categories?page=1",
    "path": "https://student.valuxapps.com/api/categories",
    "per_page": 35,
    "prev_page_url": "https://student.valuxapps.com/api/categories?page=1",
    "to": 5,
    "total": 5
  }
}
*/

  bool? status;
  String? message;
  CategoriesModelData? data;

  CategoriesModel({
    this.status,
    this.message,
    this.data,
  });
  CategoriesModel.fromJson(Map<String, dynamic> json) {
    status = json[_jsonKeyCategoriesModelStatus];
    message = json[_jsonKeyCategoriesModelMessage]?.toString();
    data = (json[_jsonKeyCategoriesModelData] != null && (json[_jsonKeyCategoriesModelData] is Map)) ? CategoriesModelData.fromJson(json[_jsonKeyCategoriesModelData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyCategoriesModelStatus] = status;
    data[_jsonKeyCategoriesModelMessage] = message;
    if (data != null) {
      data[_jsonKeyCategoriesModelData] = this.data!.toJson();
    }
    return data;
  }
}
